### ISSUE TITLE
Font format

### ISSUE THREAD

**Issue by rosenrost** [RWAP/PrinterToPDF#22]
I would like to use a codepage 437 font. Are there any available? I tried these: http://forum.retroprinter.com/viewtopic.php?f=6&t=22&p=54
Unfortunately, the result looks rather like hieroglyphs or braille than CP 437.

_Update:_

The Fony tool mentioned in the forum thread does the conversion using File/Export/Binary data with 8 bits per character row.

So, I converted the Epson-PC437-US.fon this way to Epson-PC437-US.C16. But, unfortunatelly, I cannot get German umlauts being printed. For example, a simple "ü" (code 129 in code page 437) results in being ignored. As a result of that, an expected "Düsseldorf" will be "Dsseldorf" on paper.

Any help is appreciated.

**Comment by RWAP** [comment]
Support for foreign fonts etc is written into our commercial Retro-Printer package, but you should be able to replace the existing font with the one produced from our own custom font package (by exporting from Fony as you have discovered).

By default Epson printers (and hence ESC/P2) does not support characters with a character code over 127 unless you pass an ESC/P2 code to set print_uppercontrolcodes to 1 (see line 2710 of the code).  This was sometimes overcome by DIP switches on the printer.

You can do this in a print program by using `ESC m 0` or `ESC 6` (see line 4014 and line 3666) - strictly, neither work in ESC/P2 if italics is on.  

The other option is to search the code and where `print_uppercontrolcodes = 0;` appears, change this to `print_uppercontrolcodes = 1;` so that it is on by default (there are 3 instances as it gets reset following `ESC @` (reset printer)

**Comment by rosenrost** [comment]
Yes, I remember my LX-400 had those dip switches and one of it was to enable 8 bit character mode. Thank your for your information, everything is fine now.

**Comment by RWAP** [comment]
Hi - I just read your comments on https://forum.atari-home.de/index.php/topic,15874.0.html

Can you maybe update to reflect the changes - reach out to me via www.retroprinter.com (or the www.retroprinter-support.com forums too) as that would be good to discuss any issues and use with Beepi

Rich

**Comment by rosenrost** [comment]
I wrote those comments before your first answer to this issue here.

However, I made some changes to the code so far, to make it fit **my needs**, but they may be of interest for the community as well. These changes include:

- enabling the use of 8 bit characters rather than italic by default (which can be changed by commenting out the specific `#define ITALIC_CHARS_PRINTABLE` which triggers this behaviour), 
- new default margin for A4 paper sizes (portrait and landscape): 10 millimeters on each side, 20 millimeters on the left for portrait, 20 millimeters on the top for landscape to have default margins which lets you punch the printout without punching any printed content,
- pass (multiple) files to process on the command line, which is optional (defaults to `INPUT_FILENAME`),
- add a few more fonts with 8 bit support (some sort of IBM code pages).
- add a tool which converts Atari ST (GEM) 8x16 font files (no GDOS font files, but only the pure binary data which is ordered line by line rather than character by character) to the .C16 format

I know of a few other changes and bug fixes, but cannot really remember them because I made these changes at least six months ago and missed to make any notes then.

Today I checked the recent changes and added the few ones missing in my code. I can provide a pull request, so you can have a look at it.

**Comment by RWAP** [comment]
Thanks - I realised those comments were made before the query on here.

The margins need to be configurable - the ones provided are what Epson define in their standards for A4 paper.

The other options etc sound good ideas - please add a pull request and we can look at incorporating these in the main version - I could not see that you have released your own version of the code, but may be wrong!

**Comment by rosenrost** [comment]
No, I did not release it yet as it still belongs here, I think. I'll make a pull request tomorrow.
