### ISSUE TITLE
Large PDFs

### ISSUE THREAD

**Issue by acaire** [RWAP/PrinterToPDF#33]
Hi, just trying to track down large PDF sizes, and was wondering if a 150MB PDF from a 1.6KB input file (180KB intermediary PNG file) is normal?  I've investigated the changes in #6 but can't yet find any other reason for the excessive size.  Thanks!

**Comment by RWAP** [comment]
The problem is that the PNG has to be inserted as an image inside the PDF - the code uses the libHaru PDF library to create the PDF from the image, so you would have to ask the maintainer of libHaru,

As I said, the other option is to insert the text directly into the PDF which would be better for plain text, adding search functions etc, but alas I do not have time to do this and match up the necessary PDF fonts with those on an Epson printer.

**Comment by acaire** [comment]
Gotcha, appreciate the extra info - thanks!
